version: 0.2
env:
  secrets-manager:
    LOGIN: sonartest:sonartoken
    HOST: sonartest:HOST
    Organization: sonartest:Organization
    Project: sonartest:Project
phases:
  pre_build:
    commands:
      - npm config set @types:registry https://registry.npmjs.org/
      - npm install
      - npm config set @types:registry https://registry.npmjs.org/
      - npm install jest -g
      - npm install jest-sonarcloud-reporter --save-dev
      - npm install gulp-cli -g
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - CI=true npm test
      - npm sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
