version: 0.2
env:
  secrets-manager:
    LOGIN: sonartest:sonartoken
    HOST: sonartest:HOST
    Organization: sonartest:Organization
    Project: sonartest:Project
    BasicToken: sonartest:BasicToken
phases:
  pre_build:
    commands:
      - npm install
      - npm install -g sonarqube-scanner
      - npm install gulp-cli -g
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - CI=true npm test
      - sleep 5
      - "curl -H \"Authorization: Basic $BasicToken\" https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json"
      - cat result.json
      - aws s3 sync . s3://ralph-sandbox/ --delete --acl public-read
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
